ASI/fortunka/config/routes.rb
Fortunka::Application.routes.draw do
match 'auth/:provider/callback', to: 'sessions#create'
match 'auth/failure', to: redirect('/')
match 'signout', to: 'sessions#destroy', as: 'signout'

  resources :fortunes

  root :to => 'fortunes#index'
end

ASI/fortunka/app/models/fortune.rb
class Fortune < ActiveRecord::Base
  attr_accessible :quotation, :source

validates :quotation, length: {
  minimum: 20,
  maximum: 300
}

validates :source, presence: true

end

ASI/fortunka/app/models/user.rb
class User < ActiveRecord::Base
def self.from_omniauth(auth)
  where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
    user.provider = auth.provider
    user.uid = auth.uid
    user.name = auth.info.name
    user.oauth_token = auth.credentials.token
    user.oauth_expires_at = Time.at(auth.credentials.expires_at)
    user.save!
  end
end

end

ASI/fortunka/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery


private

def current_user
  @current_user ||= User.find(session[:user_id]) if session[:user_id]
end
helper_method :current_user
end

ASI/fortunka/app/controllers/fortunes_controller.rb
class FortunesController < ApplicationController
  # GET /fortunes
  # GET /fortunes.json
  def index
    @fortunes = Fortune.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @fortunes }
    end
  end

  # GET /fortunes/1
  # GET /fortunes/1.json
  def show
    @fortune = Fortune.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @fortune }
    end
  end

  # GET /fortunes/new
  # GET /fortunes/new.json
  def new
    @fortune = Fortune.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @fortune }
    end
  end

  # GET /fortunes/1/edit
  def edit
    @fortune = Fortune.find(params[:id])
  end

  # POST /fortunes
  # POST /fortunes.json
  def create
    @fortune = Fortune.new(params[:fortune])

    respond_to do |format|
      if @fortune.save
        format.html { redirect_to @fortune, notice: 'Dowcip dodany!' }
        format.json { render json: @fortune, status: :created, location: @fortune }
      else
        format.html { render action: "new" }
        format.json { render json: @fortune.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /fortunes/1
  # PUT /fortunes/1.json
  def update
    @fortune = Fortune.find(params[:id])

    respond_to do |format|
      if @fortune.update_attributes(params[:fortune])
        format.html { redirect_to @fortune, notice: 'Dowcip uaktualniony!' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @fortune.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fortunes/1
  # DELETE /fortunes/1.json
  def destroy
    @fortune = Fortune.find(params[:id])
    @fortune.destroy

    respond_to do |format|
      format.html { redirect_to fortunes_url }
      format.json { head :no_content }
    end
  end
end

ASI/fortunka/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to root_url
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end
end

ASI/fortunka/app/helpers/application_helper.rb
module ApplicationHelper
end

ASI/fortunka/app/helpers/fortunes_helper.rb
module FortunesHelper
end

ASI/fortunka/app/views/fortunes/_form.html.erb
<%= simple_form_for(@fortune) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :quotation %>
    <%= f.input :source %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

ASI/fortunka/app/views/fortunes/edit.html.erb
<h1>Edycja</h1>

<%= render 'form' %>

<%= link_to 'Edycja', @fortune %> |
<%= link_to 'Usun', fortunes_path %>

ASI/fortunka/app/views/fortunes/index.html.erb
<%- model_class = Fortune -%>
<div class="page-header">
  <h1>Dowcipy</h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th>Tresc</th>
      <th>Dodal</th>
      <th>Nadeslano</th>
      <th>Opcje</th>
    </tr>
  </thead>
  <tbody>
    <% @fortunes.each do |fortune| %>
      <tr>
        <td><%= link_to fortune.id, fortune_path(fortune) %></td>
        <td><%= fortune.quotation %></td>
        <td><%= fortune.source %></td>
        <td><%=l fortune.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("Edycja")),
                      edit_fortune_path(fortune), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("Usun")),
                      fortune_path(fortune),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Czy chcesz przejsc dalej?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("Dodaj nowy")),
            new_fortune_path,
            :class => 'btn btn-primary' %>

ASI/fortunka/app/views/fortunes/new.html.erb
<h1>Nowy dowcip</h1>

<%= render 'form' %>

<%= link_to 'Cofnij', fortunes_path %>

ASI/fortunka/app/views/fortunes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Dowcip: </b>
  <%= @fortune.quotation %>
</p>

<p>
  <b>Przeslal: </b>
  <%= @fortune.source %>
</p>


<%= link_to 'Edytuj', edit_fortune_path(@fortune) %> |
<%= link_to 'Cofnij', fortunes_path %>

ASI/fortunka/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Fortunka" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
<!--    <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %> -->

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
<!--    <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %> -->

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
<!--    <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %> -->

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
<!--    <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %> -->

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
<!--    <%= favicon_link_tag 'images/favicon.ico', :rel => 'shortcut icon' %> -->
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">

<div id="user_nav">
  <% if current_user %>
    Zalogowany jako <strong><%= current_user.name %></strong>!
    <%= link_to "Wyloguj", signout_path, id: "sign_out" %>
  <% else %>
    <%= link_to "Zaloguj przez Facebook", "/auth/facebook", id: "Zaloguj" %>
  <% end %>
</div>

          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>

          <div class="container nav-collapse">
            <ul class="nav">
              <li></li>
              <li>
</li>
              <li></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>



    <div class="container">
        <div class="row">
          <div class="span9">
             <%= yield %>
          </div>
          <div class="span3">
           
            </div><!--/.well -->
          </div><!--/span-->
        </div><!--/row-->

      <footer>
        <p>&copy; Darek Jaroszewski 2013</p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>
    <%= render partial: 'shared/navbar' %>
  </body>
</html>

ASI/fortunka/app/views/layouts/fixed.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Fortunka" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'images/favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Fortunka</a>
          <div class="container nav-collapse">
            <ul class="nav">
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
        <div class="row">
          <div class="span9">
             <%= yield %>
          </div>
          <div class="span3">
            <div class="well sidebar-nav">
              <h3>Sidebar</h3>
              <ul class="nav nav-list">
                <li class="nav-header">Sidebar</li>
                <li><%= link_to "Link1", "/path1"  %></li>
                <li><%= link_to "Link2", "/path2"  %></li>
                <li><%= link_to "Link3", "/path3"  %></li>
              </ul>
            </div><!--/.well -->
          </div><!--/span-->
        </div><!--/row-->

      <footer>
        <p>&copy; Company 2012</p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

ASI/fortunka/app/views/shared/_navbar.html.erb
<div class="navbar">
  <div class="navbar-inner">
    <div class="container">
      
      <p>
       
      </p>
      <ul class="nav pull-right">
        
      </ul>
    </div>
  </div>
</div>